server:
  port: 6001
spring:
  profiles:
    active:
      - dev
  application:
    name: game-gateway
  redis:
    host: 127.0.0.1
    password: root
    port: 6379
    timeout: 500
  #    jedis:
  #      pool:
  #        max-idle: 50
  #        max-wait: 500
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
        register-enabled: true
        server-addr: 127.0.0.1:9090
        namespace: b8142ed2-6e55-49f3-9e7a-ca83ed3679b6
        metadata:
          gamePort: ${game.gateway.server.config.port}
          #gameProxyHost: 127.0.0.1
          #gameProxyPort: 16001
          serverId: ${game.gateway.server.config.server-id}
          serviceId: ${game.gateway.server.config.service-id}
    bus:
      enabled: true
      stream:
        kafka:
          binder:
            brokers:
              - 127.0.0.1:9092  #配置Kafka地址
  kafka:
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer  # 指定生产者的Key的序列化方式
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: gateway-group
game:
  gateway:
    server:
      config:
        port: 16001  # 游戏网关的长连接端口，这里的数据是自定义配置。
        boss-thread-count: 1
        work-thread-count: 4
        server-id: 1001
        service-id: 1
        business-game-message-topic: business-game-message-topic # 向游戏服务发送消息 的Topic前缀
        gateway-game-message-topic: gateway-game-message-topic-${game.gateway.server.config.server-id}
        #接收游戏服务响应消息的Topic
        rb-gateway-game-message-topic: rb-gateway-game-message-topic-${game.gateway.server.config.server-id}
        #专门接收RaidBattle响应回客户端的Topic
    waitlines:
      #排队设定
      config:
        #同一秒 [登陆] 允许做大的请求令牌 俗称QPS
        maxPermits: 10
        #令牌数取得率变成恒速前的热身时间  最大存量的同时,初启动时的令牌数也是 = maxPermits * warmUpPeriodSeconds个
        warmUpPeriodSeconds: 60
        #同时排队的最大人数
        maxWaitingRequests: 1000
        #未登陆的player最多在队列里发呆多少秒后,踢出
        fakeSeconds: 1800
        #每多少秒检查一次队列
        checkDelaySeconds: 1800
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"