// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ThirdMsgBody.proto

package com.mygame.game.message.body;

public final class ThirdMsgBody {
  private ThirdMsgBody() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ThirdMsgRequestBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ThirdMsgRequestBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string value1 = 1;</code>
     */
    boolean hasValue1();
    /**
     * <code>optional string value1 = 1;</code>
     */
    java.lang.String getValue1();
    /**
     * <code>optional string value1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getValue1Bytes();

    /**
     * <pre>
     *表示一个long类型的值
     * </pre>
     *
     * <code>optional int64 value2 = 2;</code>
     */
    boolean hasValue2();
    /**
     * <pre>
     *表示一个long类型的值
     * </pre>
     *
     * <code>optional int64 value2 = 2;</code>
     */
    long getValue2();
  }
  /**
   * <pre>
   *请求消息消息体
   * </pre>
   *
   * Protobuf type {@code ThirdMsgRequestBody}
   */
  public  static final class ThirdMsgRequestBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ThirdMsgRequestBody)
      ThirdMsgRequestBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ThirdMsgRequestBody.newBuilder() to construct.
    private ThirdMsgRequestBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ThirdMsgRequestBody() {
      value1_ = "";
      value2_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ThirdMsgRequestBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              value1_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value2_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgRequestBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgRequestBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody.class, com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody.Builder.class);
    }

    private int bitField0_;
    public static final int VALUE1_FIELD_NUMBER = 1;
    private volatile java.lang.Object value1_;
    /**
     * <code>optional string value1 = 1;</code>
     */
    public boolean hasValue1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string value1 = 1;</code>
     */
    public java.lang.String getValue1() {
      java.lang.Object ref = value1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValue1Bytes() {
      java.lang.Object ref = value1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE2_FIELD_NUMBER = 2;
    private long value2_;
    /**
     * <pre>
     *表示一个long类型的值
     * </pre>
     *
     * <code>optional int64 value2 = 2;</code>
     */
    public boolean hasValue2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *表示一个long类型的值
     * </pre>
     *
     * <code>optional int64 value2 = 2;</code>
     */
    public long getValue2() {
      return value2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, value2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, value2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody)) {
        return super.equals(obj);
      }
      com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody other = (com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody) obj;

      boolean result = true;
      result = result && (hasValue1() == other.hasValue1());
      if (hasValue1()) {
        result = result && getValue1()
            .equals(other.getValue1());
      }
      result = result && (hasValue2() == other.hasValue2());
      if (hasValue2()) {
        result = result && (getValue2()
            == other.getValue2());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasValue1()) {
        hash = (37 * hash) + VALUE1_FIELD_NUMBER;
        hash = (53 * hash) + getValue1().hashCode();
      }
      if (hasValue2()) {
        hash = (37 * hash) + VALUE2_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValue2());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求消息消息体
     * </pre>
     *
     * Protobuf type {@code ThirdMsgRequestBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ThirdMsgRequestBody)
        com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgRequestBody_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgRequestBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody.class, com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody.Builder.class);
      }

      // Construct using com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgRequestBody_descriptor;
      }

      @java.lang.Override
      public com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody getDefaultInstanceForType() {
        return com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody.getDefaultInstance();
      }

      @java.lang.Override
      public com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody build() {
        com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody buildPartial() {
        com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody result = new com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value1_ = value1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value2_ = value2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody) {
          return mergeFrom((com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody other) {
        if (other == com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody.getDefaultInstance()) return this;
        if (other.hasValue1()) {
          bitField0_ |= 0x00000001;
          value1_ = other.value1_;
          onChanged();
        }
        if (other.hasValue2()) {
          setValue2(other.getValue2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object value1_ = "";
      /**
       * <code>optional string value1 = 1;</code>
       */
      public boolean hasValue1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public java.lang.String getValue1() {
        java.lang.Object ref = value1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValue1Bytes() {
        java.lang.Object ref = value1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public Builder setValue1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public Builder clearValue1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value1_ = getDefaultInstance().getValue1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public Builder setValue1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }

      private long value2_ ;
      /**
       * <pre>
       *表示一个long类型的值
       * </pre>
       *
       * <code>optional int64 value2 = 2;</code>
       */
      public boolean hasValue2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *表示一个long类型的值
       * </pre>
       *
       * <code>optional int64 value2 = 2;</code>
       */
      public long getValue2() {
        return value2_;
      }
      /**
       * <pre>
       *表示一个long类型的值
       * </pre>
       *
       * <code>optional int64 value2 = 2;</code>
       */
      public Builder setValue2(long value) {
        bitField0_ |= 0x00000002;
        value2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *表示一个long类型的值
       * </pre>
       *
       * <code>optional int64 value2 = 2;</code>
       */
      public Builder clearValue2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value2_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ThirdMsgRequestBody)
    }

    // @@protoc_insertion_point(class_scope:ThirdMsgRequestBody)
    private static final com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody();
    }

    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ThirdMsgRequestBody>
        PARSER = new com.google.protobuf.AbstractParser<ThirdMsgRequestBody>() {
      @java.lang.Override
      public ThirdMsgRequestBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ThirdMsgRequestBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ThirdMsgRequestBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ThirdMsgRequestBody> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mygame.game.message.body.ThirdMsgBody.ThirdMsgRequestBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ThirdMsgResponseBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ThirdMsgResponseBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string value1 = 1;</code>
     */
    boolean hasValue1();
    /**
     * <code>optional string value1 = 1;</code>
     */
    java.lang.String getValue1();
    /**
     * <code>optional string value1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getValue1Bytes();

    /**
     * <pre>
     *表示一个int类型的值
     * </pre>
     *
     * <code>optional int32 value2 = 2;</code>
     */
    boolean hasValue2();
    /**
     * <pre>
     *表示一个int类型的值
     * </pre>
     *
     * <code>optional int32 value2 = 2;</code>
     */
    int getValue2();

    /**
     * <code>optional string value3 = 3;</code>
     */
    boolean hasValue3();
    /**
     * <code>optional string value3 = 3;</code>
     */
    java.lang.String getValue3();
    /**
     * <code>optional string value3 = 3;</code>
     */
    com.google.protobuf.ByteString
        getValue3Bytes();
  }
  /**
   * <pre>
   *响应消息消息体
   * </pre>
   *
   * Protobuf type {@code ThirdMsgResponseBody}
   */
  public  static final class ThirdMsgResponseBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ThirdMsgResponseBody)
      ThirdMsgResponseBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ThirdMsgResponseBody.newBuilder() to construct.
    private ThirdMsgResponseBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ThirdMsgResponseBody() {
      value1_ = "";
      value2_ = 0;
      value3_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ThirdMsgResponseBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              value1_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value2_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              value3_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgResponseBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgResponseBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody.class, com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody.Builder.class);
    }

    private int bitField0_;
    public static final int VALUE1_FIELD_NUMBER = 1;
    private volatile java.lang.Object value1_;
    /**
     * <code>optional string value1 = 1;</code>
     */
    public boolean hasValue1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string value1 = 1;</code>
     */
    public java.lang.String getValue1() {
      java.lang.Object ref = value1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValue1Bytes() {
      java.lang.Object ref = value1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE2_FIELD_NUMBER = 2;
    private int value2_;
    /**
     * <pre>
     *表示一个int类型的值
     * </pre>
     *
     * <code>optional int32 value2 = 2;</code>
     */
    public boolean hasValue2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *表示一个int类型的值
     * </pre>
     *
     * <code>optional int32 value2 = 2;</code>
     */
    public int getValue2() {
      return value2_;
    }

    public static final int VALUE3_FIELD_NUMBER = 3;
    private volatile java.lang.Object value3_;
    /**
     * <code>optional string value3 = 3;</code>
     */
    public boolean hasValue3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string value3 = 3;</code>
     */
    public java.lang.String getValue3() {
      java.lang.Object ref = value3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValue3Bytes() {
      java.lang.Object ref = value3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value3_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value3_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody)) {
        return super.equals(obj);
      }
      com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody other = (com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody) obj;

      boolean result = true;
      result = result && (hasValue1() == other.hasValue1());
      if (hasValue1()) {
        result = result && getValue1()
            .equals(other.getValue1());
      }
      result = result && (hasValue2() == other.hasValue2());
      if (hasValue2()) {
        result = result && (getValue2()
            == other.getValue2());
      }
      result = result && (hasValue3() == other.hasValue3());
      if (hasValue3()) {
        result = result && getValue3()
            .equals(other.getValue3());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasValue1()) {
        hash = (37 * hash) + VALUE1_FIELD_NUMBER;
        hash = (53 * hash) + getValue1().hashCode();
      }
      if (hasValue2()) {
        hash = (37 * hash) + VALUE2_FIELD_NUMBER;
        hash = (53 * hash) + getValue2();
      }
      if (hasValue3()) {
        hash = (37 * hash) + VALUE3_FIELD_NUMBER;
        hash = (53 * hash) + getValue3().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应消息消息体
     * </pre>
     *
     * Protobuf type {@code ThirdMsgResponseBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ThirdMsgResponseBody)
        com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgResponseBody_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgResponseBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody.class, com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody.Builder.class);
      }

      // Construct using com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        value3_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mygame.game.message.body.ThirdMsgBody.internal_static_ThirdMsgResponseBody_descriptor;
      }

      @java.lang.Override
      public com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody getDefaultInstanceForType() {
        return com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody.getDefaultInstance();
      }

      @java.lang.Override
      public com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody build() {
        com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody buildPartial() {
        com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody result = new com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value1_ = value1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value2_ = value2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value3_ = value3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody) {
          return mergeFrom((com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody other) {
        if (other == com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody.getDefaultInstance()) return this;
        if (other.hasValue1()) {
          bitField0_ |= 0x00000001;
          value1_ = other.value1_;
          onChanged();
        }
        if (other.hasValue2()) {
          setValue2(other.getValue2());
        }
        if (other.hasValue3()) {
          bitField0_ |= 0x00000004;
          value3_ = other.value3_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object value1_ = "";
      /**
       * <code>optional string value1 = 1;</code>
       */
      public boolean hasValue1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public java.lang.String getValue1() {
        java.lang.Object ref = value1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValue1Bytes() {
        java.lang.Object ref = value1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public Builder setValue1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public Builder clearValue1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value1_ = getDefaultInstance().getValue1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value1 = 1;</code>
       */
      public Builder setValue1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value1_ = value;
        onChanged();
        return this;
      }

      private int value2_ ;
      /**
       * <pre>
       *表示一个int类型的值
       * </pre>
       *
       * <code>optional int32 value2 = 2;</code>
       */
      public boolean hasValue2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *表示一个int类型的值
       * </pre>
       *
       * <code>optional int32 value2 = 2;</code>
       */
      public int getValue2() {
        return value2_;
      }
      /**
       * <pre>
       *表示一个int类型的值
       * </pre>
       *
       * <code>optional int32 value2 = 2;</code>
       */
      public Builder setValue2(int value) {
        bitField0_ |= 0x00000002;
        value2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *表示一个int类型的值
       * </pre>
       *
       * <code>optional int32 value2 = 2;</code>
       */
      public Builder clearValue2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value2_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value3_ = "";
      /**
       * <code>optional string value3 = 3;</code>
       */
      public boolean hasValue3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string value3 = 3;</code>
       */
      public java.lang.String getValue3() {
        java.lang.Object ref = value3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value3_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value3 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValue3Bytes() {
        java.lang.Object ref = value3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value3 = 3;</code>
       */
      public Builder setValue3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value3 = 3;</code>
       */
      public Builder clearValue3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value3_ = getDefaultInstance().getValue3();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value3 = 3;</code>
       */
      public Builder setValue3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value3_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ThirdMsgResponseBody)
    }

    // @@protoc_insertion_point(class_scope:ThirdMsgResponseBody)
    private static final com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody();
    }

    public static com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ThirdMsgResponseBody>
        PARSER = new com.google.protobuf.AbstractParser<ThirdMsgResponseBody>() {
      @java.lang.Override
      public ThirdMsgResponseBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ThirdMsgResponseBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ThirdMsgResponseBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ThirdMsgResponseBody> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mygame.game.message.body.ThirdMsgBody.ThirdMsgResponseBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThirdMsgRequestBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThirdMsgRequestBody_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThirdMsgResponseBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThirdMsgResponseBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ThirdMsgBody.proto\"5\n\023ThirdMsgRequestB" +
      "ody\022\016\n\006value1\030\001 \001(\t\022\016\n\006value2\030\002 \001(\003\"F\n\024T" +
      "hirdMsgResponseBody\022\016\n\006value1\030\001 \001(\t\022\016\n\006v" +
      "alue2\030\002 \001(\005\022\016\n\006value3\030\003 \001(\tB,\n\034com.mygam" +
      "e.game.message.bodyB\014ThirdMsgBody"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ThirdMsgRequestBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ThirdMsgRequestBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThirdMsgRequestBody_descriptor,
        new java.lang.String[] { "Value1", "Value2", });
    internal_static_ThirdMsgResponseBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ThirdMsgResponseBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThirdMsgResponseBody_descriptor,
        new java.lang.String[] { "Value1", "Value2", "Value3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
